/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fragmentacion_vertical;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author 706
 */
public class Inicio extends javax.swing.JFrame {
    Integer matUse[][] = new Integer[4][4];
    Integer matAcc[][] = new Integer[4][3];
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        agregarValidaciones();
    }
    
    public void obtenerMatUse(){
        matUse[0][0] = Integer.parseInt(matUse1.getText());
        matUse[0][1] = Integer.parseInt(matUse2.getText());
        matUse[0][2] = Integer.parseInt(matUse3.getText());
        matUse[0][3] = Integer.parseInt(matUse4.getText());
        
        matUse[1][0] = Integer.parseInt(matUse5.getText());
        matUse[1][1] = Integer.parseInt(matUse6.getText());
        matUse[1][2] = Integer.parseInt(matUse7.getText());
        matUse[1][3] = Integer.parseInt(matUse8.getText());   
        
        matUse[2][0] = Integer.parseInt(matUse9.getText());
        matUse[2][1] = Integer.parseInt(matUse10.getText());
        matUse[2][2] = Integer.parseInt(matUse11.getText());
        matUse[2][3] = Integer.parseInt(matUse12.getText());

        matUse[3][0] = Integer.parseInt(matUse13.getText());
        matUse[3][1] = Integer.parseInt(matUse14.getText());
        matUse[3][2] = Integer.parseInt(matUse15.getText());
        matUse[3][3] = Integer.parseInt(matUse16.getText());        
    }
    public void obtenerMatAcc(){
        matAcc[0][0] = Integer.parseInt(matAcc1.getText());
        matAcc[0][1] = Integer.parseInt(matAcc2.getText());
        matAcc[0][2] = Integer.parseInt(matAcc3.getText());
        
        matAcc[1][0] = Integer.parseInt(matAcc4.getText());
        matAcc[1][1] = Integer.parseInt(matAcc5.getText());
        matAcc[1][2] = Integer.parseInt(matAcc6.getText());

        matAcc[2][0] = Integer.parseInt(matAcc7.getText());
        matAcc[2][1] = Integer.parseInt(matAcc8.getText());
        matAcc[2][2] = Integer.parseInt(matAcc9.getText());

        matAcc[3][0] = Integer.parseInt(matAcc10.getText());
        matAcc[3][1] = Integer.parseInt(matAcc11.getText());
        matAcc[3][2] = Integer.parseInt(matAcc12.getText());   
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        matUse1 = new javax.swing.JTextField();
        matUse2 = new javax.swing.JTextField();
        matUse3 = new javax.swing.JTextField();
        matUse4 = new javax.swing.JTextField();
        matUse5 = new javax.swing.JTextField();
        matUse6 = new javax.swing.JTextField();
        matUse7 = new javax.swing.JTextField();
        matUse8 = new javax.swing.JTextField();
        matUse9 = new javax.swing.JTextField();
        matUse10 = new javax.swing.JTextField();
        matUse11 = new javax.swing.JTextField();
        matUse12 = new javax.swing.JTextField();
        matUse13 = new javax.swing.JTextField();
        matUse14 = new javax.swing.JTextField();
        matUse15 = new javax.swing.JTextField();
        matUse16 = new javax.swing.JTextField();
        matAcc1 = new javax.swing.JTextField();
        matAcc2 = new javax.swing.JTextField();
        matAcc3 = new javax.swing.JTextField();
        matAcc4 = new javax.swing.JTextField();
        matAcc5 = new javax.swing.JTextField();
        matAcc6 = new javax.swing.JTextField();
        matAcc7 = new javax.swing.JTextField();
        matAcc8 = new javax.swing.JTextField();
        matAcc9 = new javax.swing.JTextField();
        matAcc10 = new javax.swing.JTextField();
        matAcc11 = new javax.swing.JTextField();
        matAcc12 = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        matAA1 = new javax.swing.JTextField();
        matAA2 = new javax.swing.JTextField();
        matAA3 = new javax.swing.JTextField();
        matAA4 = new javax.swing.JTextField();
        matAA5 = new javax.swing.JTextField();
        matAA6 = new javax.swing.JTextField();
        matAA7 = new javax.swing.JTextField();
        matAA8 = new javax.swing.JTextField();
        matAA9 = new javax.swing.JTextField();
        matAA10 = new javax.swing.JTextField();
        matAA11 = new javax.swing.JTextField();
        matAA12 = new javax.swing.JTextField();
        matAA13 = new javax.swing.JTextField();
        matAA14 = new javax.swing.JTextField();
        matAA15 = new javax.swing.JTextField();
        matAA16 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Inserte los valores para las siguientes matrices de acuerdo al sitio.");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Matriz Access");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("A1");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Matriz Use");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("A2");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("A4");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("A3");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("q1");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("q2");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("q3");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("q4");

        jLabel12.setText("S1");

        jLabel13.setText("S2");

        jLabel14.setText("S3");

        matUse1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matUse16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        matAcc12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnIniciar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        matAA1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA1.setEnabled(false);

        matAA2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA2.setEnabled(false);

        matAA3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA3.setEnabled(false);

        matAA4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA4.setEnabled(false);

        matAA5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA5.setEnabled(false);

        matAA6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA6.setEnabled(false);

        matAA7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA7.setEnabled(false);

        matAA8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA8.setEnabled(false);

        matAA9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA9.setEnabled(false);

        matAA10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA10.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA10.setEnabled(false);

        matAA11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA11.setEnabled(false);

        matAA12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA12.setEnabled(false);

        matAA13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA13.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA13.setEnabled(false);

        matAA14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA14.setEnabled(false);

        matAA15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA15.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA15.setEnabled(false);

        matAA16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        matAA16.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        matAA16.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Matriz AA");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("A4");

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("A3");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("A2");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("A1");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("A4");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("A3");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("A2");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setText("A1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matUse1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(matUse2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(matUse3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(matUse4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel5)
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel7)))
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(matUse5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(matUse6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(matUse7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(matUse9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(matUse10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(matUse12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(matUse11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(matUse8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(matUse13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matUse14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matUse15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matUse16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(matAcc4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(matAcc7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(matAcc10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(matAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(matAcc2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(matAcc3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel12)
                                    .addGap(63, 63, 63)
                                    .addComponent(jLabel13)
                                    .addGap(66, 66, 66)
                                    .addComponent(jLabel14))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matAA5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matAA9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matAA13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(matAA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(matAA2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(matAA4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel18)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel17)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel16)
                                .addGap(29, 29, 29))))
                    .addComponent(jLabel1))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel18)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(matUse1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(matUse5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(matUse9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(matUse13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matUse16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAcc12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matAA16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        try{
            obtenerMatUse();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: Debe llenar todos los campos de la matriz de Uso");
        }
        
        try{
            obtenerMatAcc();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: Debe llenar todos los campos de la matriz de Acceso");
        }        

    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField matAA1;
    private javax.swing.JTextField matAA10;
    private javax.swing.JTextField matAA11;
    private javax.swing.JTextField matAA12;
    private javax.swing.JTextField matAA13;
    private javax.swing.JTextField matAA14;
    private javax.swing.JTextField matAA15;
    private javax.swing.JTextField matAA16;
    private javax.swing.JTextField matAA2;
    private javax.swing.JTextField matAA3;
    private javax.swing.JTextField matAA4;
    private javax.swing.JTextField matAA5;
    private javax.swing.JTextField matAA6;
    private javax.swing.JTextField matAA7;
    private javax.swing.JTextField matAA8;
    private javax.swing.JTextField matAA9;
    private javax.swing.JTextField matAcc1;
    private javax.swing.JTextField matAcc10;
    private javax.swing.JTextField matAcc11;
    private javax.swing.JTextField matAcc12;
    private javax.swing.JTextField matAcc2;
    private javax.swing.JTextField matAcc3;
    private javax.swing.JTextField matAcc4;
    private javax.swing.JTextField matAcc5;
    private javax.swing.JTextField matAcc6;
    private javax.swing.JTextField matAcc7;
    private javax.swing.JTextField matAcc8;
    private javax.swing.JTextField matAcc9;
    private javax.swing.JTextField matUse1;
    private javax.swing.JTextField matUse10;
    private javax.swing.JTextField matUse11;
    private javax.swing.JTextField matUse12;
    private javax.swing.JTextField matUse13;
    private javax.swing.JTextField matUse14;
    private javax.swing.JTextField matUse15;
    private javax.swing.JTextField matUse16;
    private javax.swing.JTextField matUse2;
    private javax.swing.JTextField matUse3;
    private javax.swing.JTextField matUse4;
    private javax.swing.JTextField matUse5;
    private javax.swing.JTextField matUse6;
    private javax.swing.JTextField matUse7;
    private javax.swing.JTextField matUse8;
    private javax.swing.JTextField matUse9;
    // End of variables declaration//GEN-END:variables
public void agregarValidaciones(){
    matUse1.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse2.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });    
    matUse3.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse4.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse5.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse6.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse7.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse2.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse2.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse2.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse8.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse9.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse10.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });    
    matUse11.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse12.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse13.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse14.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse15.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });
    matUse16.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarUnoCero(e);
        }
        });    
    
    matAcc1.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });     
    matAcc2.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc3.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc4.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc5.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc6.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc7.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc8.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc9.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc10.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc11.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });
    matAcc12.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
        validarEnteros(e);
        }
        });    
}

    public void validarUnoCero(KeyEvent e) {
        char c = e.getKeyChar();
        if (!('1'==c||'0'==c)) {
        getToolkit().beep();
        e.consume();
        JOptionPane.showMessageDialog(null,"Error: La matriz de Uso solo acepta 0 y 1");
        }
    }
    public void validarEnteros(KeyEvent e) {
        char c = e.getKeyChar();
        if (!(Character.isDigit(c) ||
        (c == KeyEvent.VK_BACK_SPACE) ||
        (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        e.consume();
        JOptionPane.showMessageDialog(null,"Error: La matriz de Acceso solo acepta numeros enteros");
        }
    }
}
